/// Localization Service untuk mendukung EN dan ID
class LocalizationService {
  /// Strings dalam Bahasa Indonesia dan English
  static const Map<String, Map<String, String>> strings = {
    'id': {
      'welcome': 'Halooo',
      'shopping': 'hari ini mau belanja apa nihh?',
      'search': 'Cari kaos, hoodie...',
      'filter': 'Filter',
      'sort': 'Urutkan',
      'popular': 'Produk Populer',
      'viewAll': 'Lihat Semua',
      'addToCart': 'Tambah ke Keranjang',
      'buyNow': 'Beli Sekarang',
      'price': 'Harga',
      'discount': 'Diskon',
      'cart': 'Keranjang',
      'checkout': 'Checkout',
      'payment': 'Pembayaran',
      'profile': 'Profil',
      'logout': 'Logout',
      'settings': 'Pengaturan',
      'darkMode': 'Mode Gelap',
      'language': 'Bahasa',
      'notFound': 'Produk tidak ditemukan',
      'loading': 'Memuat...',
      'error': 'Terjadi kesalahan',
      'retry': 'Coba Lagi',
      'noItems': 'Tidak ada item',
      'total': 'Total',
      'back': 'Kembali',
      'delete': 'Hapus',
      'confirm': 'Konfirmasi',
      'cancel': 'Batal',
      'save': 'Simpan',
      'update': 'Update',
      'uploadPhoto': 'Upload Foto',
      'defaultPhoto': 'Foto Default',
      'paymentMethod': 'Metode Pembayaran',
      'creditCard': 'Kartu Kredit',
      'bankTransfer': 'Transfer Bank',
      'eWallet': 'E-Wallet',
      'orderComplete': 'Pesanan Berhasil',
      'orderFailed': 'Pesanan Gagal',
      'contactInfo': 'Informasi Kontak',
      'email': 'Email',
      'emailHint': 'kamu@contoh.com',
      'orderSummary': 'Ringkasan Pesanan',
      'subtotal': 'Subtotal',
      'shipping': 'Pengiriman',
      'tax': 'Pajak',
      'totalDue': 'Total Tagihan',
      'payNow': 'Bayar Sekarang',
      'transactionId': 'Nomor Transaksi',
      'backToDashboard': 'Kembali ke Dashboard',
      'paymentSuccess': 'Pembayaran Berhasil',
    },
    'en': {
      'welcome': 'Hello',
      'shopping': 'what do you want to buy today?',
      'search': 'Search clothes, hoodies...',
      'filter': 'Filter',
      'sort': 'Sort',
      'popular': 'Popular Products',
      'viewAll': 'View All',
      'addToCart': 'Add to Cart',
      'buyNow': 'Buy Now',
      'price': 'Price',
      'discount': 'Discount',
      'cart': 'Cart',
      'checkout': 'Checkout',
      'payment': 'Payment',
      'profile': 'Profile',
      'logout': 'Logout',
      'settings': 'Settings',
      'darkMode': 'Dark Mode',
      'language': 'Language',
      'notFound': 'Product not found',
      'loading': 'Loading...',
      'error': 'An error occurred',
      'retry': 'Retry',
      'noItems': 'No items',
      'total': 'Total',
      'back': 'Back',
      'delete': 'Delete',
      'confirm': 'Confirm',
      'cancel': 'Cancel',
      'save': 'Save',
      'update': 'Update',
      'uploadPhoto': 'Upload Photo',
      'defaultPhoto': 'Default Photo',
      'paymentMethod': 'Payment Method',
      'creditCard': 'Credit Card',
      'bankTransfer': 'Bank Transfer',
      'eWallet': 'E-Wallet',
      'orderComplete': 'Order Completed',
      'orderFailed': 'Order Failed',
      'contactInfo': 'Contact Information',
      'email': 'Email',
      'emailHint': 'you@example.com',
      'orderSummary': 'Order Summary',
      'subtotal': 'Subtotal',
      'shipping': 'Shipping',
      'tax': 'Tax',
      'totalDue': 'Total due today',
      'payNow': 'Pay now',
      'transactionId': 'Transaction ID',
      'backToDashboard': 'Back to Dashboard',
      'paymentSuccess': 'Payment Successful',
    },
    // Additional languages: Spanish, French, German (basic coverage)
    'es': {
      'welcome': 'Hola',
      'shopping': '¿qué quieres comprar hoy?',
      'search': 'Buscar ropa, sudaderas...',
      'filter': 'Filtrar',
      'sort': 'Ordenar',
      'popular': 'Productos Populares',
      'viewAll': 'Ver Todo',
      'addToCart': 'Añadir al Carrito',
      'buyNow': 'Comprar Ahora',
      'price': 'Precio',
      'discount': 'Descuento',
      'cart': 'Carrito',
      'checkout': 'Pagar',
      'payment': 'Pago',
      'profile': 'Perfil',
      'logout': 'Cerrar sesión',
      'settings': 'Ajustes',
      'darkMode': 'Modo Oscuro',
      'language': 'Idioma',
      'notFound': 'Producto no encontrado',
      'loading': 'Cargando...',
      'error': 'Ocurrió un error',
      'retry': 'Reintentar',
      'noItems': 'Sin elementos',
      'total': 'Total',
      'back': 'Atrás',
      'delete': 'Eliminar',
      'confirm': 'Confirmar',
      'cancel': 'Cancelar',
      'save': 'Guardar',
      'update': 'Actualizar',
      'uploadPhoto': 'Subir Foto',
      'defaultPhoto': 'Foto por Defecto',
      'paymentMethod': 'Método de Pago',
      'creditCard': 'Tarjeta de Crédito',
      'bankTransfer': 'Transferencia Bancaria',
      'eWallet': 'Monedero Electrónico',
      'orderComplete': 'Pedido Completado',
      'orderFailed': 'Pedido Fallido',
    },
    'fr': {
      'welcome': 'Bonjour',
      'shopping': 'que voulez-vous acheter aujourd\'hui?',
      'search': 'Rechercher vêtements, sweats...',
      'filter': 'Filtrer',
      'sort': 'Trier',
      'popular': 'Produits Populaires',
      'viewAll': 'Voir tout',
      'addToCart': 'Ajouter au panier',
      'buyNow': 'Acheter maintenant',
      'price': 'Prix',
      'discount': 'Remise',
      'cart': 'Panier',
      'checkout': 'Paiement',
      'payment': 'Paiement',
      'profile': 'Profil',
      'logout': 'Se déconnecter',
      'settings': 'Paramètres',
      'darkMode': 'Mode Sombre',
      'language': 'Langue',
      'notFound': 'Produit non trouvé',
      'loading': 'Chargement...',
      'error': 'Une erreur est survenue',
      'retry': 'Réessayer',
      'noItems': 'Aucun article',
      'total': 'Total',
      'back': 'Retour',
      'delete': 'Supprimer',
      'confirm': 'Confirmer',
      'cancel': 'Annuler',
      'save': 'Enregistrer',
      'update': 'Mettre à jour',
      'uploadPhoto': 'Téléverser la photo',
      'defaultPhoto': 'Photo par défaut',
      'paymentMethod': 'Méthode de paiement',
      'creditCard': 'Carte de Crédit',
      'bankTransfer': 'Virement Bancaire',
      'eWallet': 'Portefeuille Électronique',
      'orderComplete': 'Commande Terminée',
      'orderFailed': 'Échec de la commande',
    },
    'de': {
      'welcome': 'Hallo',
      'shopping': 'Was möchtest du heute kaufen?',
      'search': 'Suche Kleidung, Hoodies...',
      'filter': 'Filtern',
      'sort': 'Sortieren',
      'popular': 'Beliebte Produkte',
      'viewAll': 'Alle anzeigen',
      'addToCart': 'In den Warenkorb',
      'buyNow': 'Jetzt kaufen',
      'price': 'Preis',
      'discount': 'Rabatt',
      'cart': 'Warenkorb',
      'checkout': 'Kasse',
      'payment': 'Zahlung',
      'profile': 'Profil',
      'logout': 'Abmelden',
      'settings': 'Einstellungen',
      'darkMode': 'Dunkler Modus',
      'language': 'Sprache',
      'notFound': 'Produkt nicht gefunden',
      'loading': 'Lädt...',
      'error': 'Ein Fehler ist aufgetreten',
      'retry': 'Erneut versuchen',
      'noItems': 'Keine Artikel',
      'total': 'Gesamt',
      'back': 'Zurück',
      'delete': 'Löschen',
      'confirm': 'Bestätigen',
      'cancel': 'Abbrechen',
      'save': 'Speichern',
      'update': 'Aktualisieren',
      'uploadPhoto': 'Foto hochladen',
      'defaultPhoto': 'Standardfoto',
      'paymentMethod': 'Zahlungsmethode',
      'creditCard': 'Kreditkarte',
      'bankTransfer': 'Banküberweisung',
      'eWallet': 'E-Wallet',
      'orderComplete': 'Bestellung abgeschlossen',
      'orderFailed': 'Bestellung fehlgeschlagen',
    },
  };

  /// Get translated string
  static String get(String language, String key) {
    return strings[language]?[key] ?? key;
  }

  /// Get translated string with arguments (if needed later)
  static String getWithArgs(
      String language, String key, Map<String, String> args) {
    String text = strings[language]?[key] ?? key;
    args.forEach((placeholder, value) {
      text = text.replaceAll('{$placeholder}', value);
    });
    return text;
  }
}
